TRUNCATE `wp_bbp_engaged_topics`;
TRUNCATE `wp_bbp_favorited_topics`;
TRUNCATE `wp_bbp_forums`;
TRUNCATE `wp_bbp_replies`;
TRUNCATE `wp_bbp_subscribed_forums`;
TRUNCATE `wp_bbp_subscribed_topics`;
TRUNCATE `wp_bbp_topics`;
TRUNCATE `wp_bbp_users`;
TRUNCATE `wp_bbp_users_roles`;
